// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");

function Index$Counter(Props) {
  var match = React.useState((function () {
          return 0;
        }));
  var setCount = match[1];
  return React.createElement("div", undefined, "counter: " + String(match[0]), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (c) {
                                    return c + 1 | 0;
                                  }));
                    })
                }, "+"), React.createElement("button", {
                  onClick: (function (param) {
                      return Curry._1(setCount, (function (c) {
                                    return c - 1 | 0;
                                  }));
                    })
                }, "-"));
}

var Counter = /* module */[/* make */Index$Counter];

ReactDOMRe.renderToElementWithId(React.createElement(Index$Counter, { }), "root");

exports.Counter = Counter;
/*  Not a pure module */
